#!/usr/bin/python
# -*- coding: utf-8 -*-

# работа с CSV-файлом в Python (последовательность)
# import csv

filename_in = 'Export.csv'  # Файл, откуда получаем значения списка
farmers = {}

# Чтение файла
# with open(filename_in, 'r') as fh:
#    for data in fh:
#     data_row = data.strip().split(',')
#     print(data_row)
#     farmers[data_row[0]] = data_row[1:]
#print(farmers)
with open(filename_in, 'r') as fh:
    for data in fh:
     data_row = data.strip().split(',')
#     print(data_row)
     farmers[data_row[0]] = data_row[1:]
print(farmers)

#zip_code = input('Введите почтовый индекс => ')
#for market in farmers[zip_code]
#    market_proj = [market[0], market[7], market[9], market[19], market[20]]

#state = input('Введите название штата => ')

#city = input('Введите название города => ')
#state = input('Введите название штата => ')

#for fmid in farmers:
#    market = farmers[fmid]
#    market_proj = [market[0], market[7], market[9], market[20]]
#    if market_proj[1] == city and market_proj[2] == state:
#      print(" ".join(market_proj))
