# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(616, 422)
        self.buttonBox1 = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox1.setGeometry(QtCore.QRect(240, 380, 341, 32))
        self.buttonBox1.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox1.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox1.setObjectName("buttonBox1")
        self.pushButton1 = QtWidgets.QPushButton(Dialog)
        self.pushButton1.setGeometry(QtCore.QRect(90, 40, 75, 24))
        self.pushButton1.setObjectName("pushButton1")
        self.toolButton1 = QtWidgets.QToolButton(Dialog)
        self.toolButton1.setGeometry(QtCore.QRect(190, 40, 22, 22))
        self.toolButton1.setObjectName("toolButton1")
        self.radioButton1 = QtWidgets.QRadioButton(Dialog)
        self.radioButton1.setGeometry(QtCore.QRect(90, 80, 89, 20))
        self.radioButton1.setObjectName("radioButton1")
        self.checkBox1 = QtWidgets.QCheckBox(Dialog)
        self.checkBox1.setGeometry(QtCore.QRect(90, 120, 76, 20))
        self.checkBox1.setObjectName("checkBox1")
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(40, 160, 511, 192))
        self.tableView.setObjectName("tableView")

        self.retranslateUi(Dialog)
        self.buttonBox1.accepted.connect(Dialog.accept)
        self.buttonBox1.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton1.setText(_translate("Dialog", "PushButton"))
        self.toolButton1.setText(_translate("Dialog", "..."))
        self.radioButton1.setText(_translate("Dialog", "RadioButton"))
        self.checkBox1.setText(_translate("Dialog", "CheckBox"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
